version: "3"
services:
  reverse-proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-reverse-proxy
    volumes:
        - ./data:/data
        - ./letsencrypt:/etc/letsencrypt
    ports:
        - '80:80' # Public HTTP Port
        - '443:443' # Public HTTPS Port
        - '81:81' # Admin Web Port
  db:
    image: mysql
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./database/:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 6yHnmju&
      MYSQL_DATABASE: wordpress_th
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    
  wordpress_th:
    depends_on:
      - db
    image: wordpress
    volumes:
      - ./www/th:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress_th

  wordpress_en:
    depends_on:
      - db
    image: wordpress
    volumes:
      - ./www/en:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress_en

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
     - db
    ports:
      - '82:80'
    environment:
      PMA_HOST: 'db'
      MYSQL_ROOT_PASSWORD: '6yHnmju&'